version: "3.5"

# shared network to let these services connect to other containerized openstates services
networks:
  openstates-network:
      name: openstates-network

services:
  core:
    build: .
    environment:
    - DATABASE_URL=postgres://pgbouncer:42571allahis1@34.118.205.29:5432/civiqa-sql-db-1
    - OS_PEOPLE_DIRECTORY=/opt/people
    volumes:
    - .:/opt/openstates-core
    - ../people:/opt/people
    entrypoint: ["poetry", "run"]
    networks:
      - openstates-network
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=test
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d test -U test"]
      interval: 10s
      timeout: 5s
      retries: 5
