# Generated by Django 4.1.1 on 2022-10-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0058_alter_organization_classification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jurisdiction",
            name="classification",
            field=models.CharField(
                choices=[
                    ("school_district", "School district"),
                    ("municipality", "Municipality"),
                    ("county", "County"),
                    ("state", "State"),
                    ("country", "Country"),
                ],
                db_index=True,
                default="state",
                help_text="The type of Jurisdiction being defined.",
                max_length=50,
            ),
        ),
    ]
