# Generated by Django 4.1.1 on 2022-11-06 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0059_alter_jurisdiction_classification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="post",
            field=models.ForeignKey(
                blank=True,
                help_text="\tThe Post held by the member in the Organization.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="memberships",
                to="data.post",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="classification",
            field=models.CharField(
                blank=True,
                choices=[
                    ("legislature", "Legislature"),
                    ("executive", "Executive"),
                    ("upper", "Upper Chamber"),
                    ("lower", "Lower Chamber"),
                    ("party", "Party"),
                    ("committee", "Committee"),
                    ("government", "Government"),
                    ("subcommittee", "Subcommittee"),
                    ("judicial", "Judicial"),
                    ("school", "School"),
                    ("governing_board", "Governing board"),
                    ("administrative", "Administrative"),
                    ("advisory", "Advisory"),
                    ("managerial", "Managerial"),
                    ("police", "Police"),
                    ("", "Unknown"),
                ],
                help_text="The type of Organization being defined.",
                max_length=100,
            ),
        ),
    ]
