# Generated by Django 4.1.1 on 2023-12-12 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0062_auto_20231023_2355"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrapereport",
            name="legislative_session",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="data.legislativesession",
            ),
        ),
    ]
