# Generated by Django 4.1.1 on 2023-12-13 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0063_scrapereport_legislative_session"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillProcessingResult",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "legislative_session",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.legislativesession",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bill_processing_results",
                        to="data.runplan",
                    ),
                ),
            ],
        ),
    ]
