# Generated by Django 4.1.1 on 2023-12-14 00:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0066_rename_plan_billprocessingresult_run_plan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="billprocessingresult",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
