# Generated by Django 4.1.1 on 2023-12-16 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0068_billprocessingresult_legislative_sessions_processed_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="runplan",
            name="legislative_session",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="data.legislativesession",
            ),
        ),
    ]
