# Generated by Django 4.1.1 on 2023-12-16 10:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0069_runplan_legislative_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessiondataqualityreport",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
