# Generated by Django 4.1.1 on 2023-12-17 12:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0070_sessiondataqualityreport_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonScrapedName",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("value", models.CharField(db_index=True, max_length=300)),
                ("approved", models.BooleanField(default=False)),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scraped_names",
                        to="data.membership",
                    ),
                ),
            ],
            options={
                "db_table": "opencivicdata_personscrapedname",
                "unique_together": {("membership", "value")},
            },
        ),
    ]
