# Generated by Django 4.1.1 on 2023-12-18 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0073_alter_personscrapedname_organization"),
    ]

    operations = [
        migrations.RenameField(
            model_name="importobjects",
            old_name="report",
            new_name="plan",
        ),
        migrations.AddField(
            model_name="sessiondataqualityreport",
            name="run_plan",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="session_data_quality_report",
                to="data.runplan",
            ),
        ),
    ]
