# Generated by Django 4.1.1 on 2023-12-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0074_rename_report_importobjects_plan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="personscrapedname",
            name="vote_ids",
            field=models.JSONField(default=list),
        ),
    ]
