# Generated by Django 4.1.1 on 2023-12-19 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0077_personscrapednamematch_bill_sponsorship_ids"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PersonScrapedNameMatch",
            new_name="ScrapedNameMatch",
        ),
        migrations.AlterModelOptions(
            name="scrapednamematch",
            options={"verbose_name_plural": "scraped name matches"},
        ),
        migrations.AlterModelTable(
            name="scrapednamematch",
            table="opencivicdata_scrapednamematch",
        ),
    ]
