# Generated by Django 4.1.1 on 2023-12-19 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0078_rename_personscrapednamematch_scrapednamematch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrapednamematch",
            name="legislative_session",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scraped_names",
                to="data.legislativesession",
            ),
        ),
        migrations.AlterField(
            model_name="scrapednamematch",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scraped_names",
                to="data.organization",
            ),
        ),
    ]
