# Generated by Django 4.1.1 on 2023-12-19 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0079_scrapednamematch_legislative_session_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scrapednamematch",
            name="legislative_session",
        ),
        migrations.AlterField(
            model_name="scrapednamematch",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scraped_names",
                to="data.organization",
            ),
        ),
    ]
