# Generated by Django 4.1.1 on 2023-12-19 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0081_alter_scrapednamematch_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scrapednamematch",
            name="legislative_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scraped_names",
                to="data.legislativesession",
            ),
        ),
    ]
