# Generated by Django 4.1.1 on 2023-12-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0083_alter_runplan_legislative_session_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="runplan",
            name="end_time",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="runplan",
            name="start_time",
            field=models.DateTimeField(db_index=True),
        ),
    ]
