# Generated by Django 4.1.1 on 2023-12-20 01:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0084_alter_runplan_end_time_alter_runplan_start_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScrapedNameUnresolvedMatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("value", models.CharField(db_index=True, max_length=300)),
                ("vote_ids", models.JSONField(default=list)),
                ("bill_sponsorship_ids", models.JSONField(default=list)),
            ],
            options={
                "db_table": "opencivicdata_scrapednameunresolvedmatch",
            },
        ),
        migrations.CreateModel(
            name="ScrapedNameUnresolvedMatchOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("score", models.FloatField(default=None, null=True)),
            ],
            options={
                "db_table": "opencivicdata_scrapednameunresolvedmatchoption",
            },
        ),
        migrations.RemoveField(
            model_name="billprocessingresult",
            name="stats_calculated_legislative_session_count",
        ),
        migrations.AddConstraint(
            model_name="scrapednamematch",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("matched_membership__isnull", False),
                    ("matched_organization__isnull", False),
                    _connector="OR",
                ),
                name="scraped_name_match_membership_xor_organization",
            ),
        ),
        migrations.AddField(
            model_name="scrapednameunresolvedmatchoption",
            name="membership",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scraped_name_unresolved_match_options",
                to="data.membership",
            ),
        ),
        migrations.AddField(
            model_name="scrapednameunresolvedmatchoption",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scraped_name_unresolved_match_options",
                to="data.organization",
            ),
        ),
        migrations.AddField(
            model_name="scrapednameunresolvedmatchoption",
            name="scraped_name_unresolved_match",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="data.scrapednameunresolvedmatch",
            ),
        ),
        migrations.AddField(
            model_name="scrapednameunresolvedmatch",
            name="chosen_option",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chosen",
                to="data.scrapednameunresolvedmatchoption",
            ),
        ),
        migrations.AddField(
            model_name="scrapednameunresolvedmatch",
            name="legislative_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scraped_name_unresolved_matches",
                to="data.legislativesession",
            ),
        ),
        migrations.AddField(
            model_name="scrapednamematch",
            name="from_unresolved_match",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matched_name",
                to="data.scrapednameunresolvedmatch",
            ),
        ),
        migrations.AddConstraint(
            model_name="scrapednameunresolvedmatchoption",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("membership__isnull", False),
                    ("organization__isnull", False),
                    _connector="OR",
                ),
                name="scraped_name_unresolved_match_option_membership_xor_organization",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="scrapednameunresolvedmatchoption",
            unique_together={("scraped_name_unresolved_match", "membership")},
        ),
        migrations.AlterUniqueTogether(
            name="scrapednameunresolvedmatch",
            unique_together={("legislative_session", "value")},
        ),
    ]
