# Generated by Django 4.1.1 on 2023-12-20 12:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        (
            "data",
            "0087_remove_scrapednameunresolvedmatchoption_scraped_name_unresolved_match_option_membership_xor_organiza",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="scrapednamematch",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
