# Generated by Django 4.1.1 on 2023-12-20 13:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0090_scrapednameunresolvedmatch_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="scrapednamematch",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="scrapednamematch",
            name="from_unresolved_match",
        ),
        migrations.RemoveField(
            model_name="scrapednamematch",
            name="legislative_session",
        ),
        migrations.RemoveField(
            model_name="scrapednamematch",
            name="matched_membership",
        ),
        migrations.RemoveField(
            model_name="scrapednamematch",
            name="matched_organization",
        ),
        migrations.AlterUniqueTogether(
            name="scrapednameunresolvedmatch",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="scrapednameunresolvedmatch",
            name="chosen_option",
        ),
        migrations.RemoveField(
            model_name="scrapednameunresolvedmatch",
            name="legislative_session",
        ),
        migrations.AlterUniqueTogether(
            name="scrapednameunresolvedmatchoption",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="scrapednameunresolvedmatchoption",
            name="membership",
        ),
        migrations.RemoveField(
            model_name="scrapednameunresolvedmatchoption",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="scrapednameunresolvedmatchoption",
            name="unresolved_match",
        ),
        migrations.DeleteModel(
            name="BillProcessingResult",
        ),
        migrations.DeleteModel(
            name="ScrapedNameMatch",
        ),
        migrations.DeleteModel(
            name="ScrapedNameUnresolvedMatch",
        ),
        migrations.DeleteModel(
            name="ScrapedNameUnresolvedMatchOption",
        ),
    ]
