# Generated by Django 4.1.1 on 2023-12-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0093_billsponsorship_person_organization_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personvote",
            name="scraped_name_match_id",
            field=models.PositiveIntegerField(db_index=True, null=True),
        ),
    ]
