# Generated by Django 4.1.1 on 2023-12-25 23:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0094_alter_personvote_scraped_name_match_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PersonName",
            new_name="OtherName",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="other_names",
        ),
    ]
