# Generated by Django 4.1.1 on 2023-12-25 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0095_rename_personname_othername_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="othername",
            name="organization",
            field=models.ForeignKey(
                help_text="A link to the Organization connected to this alternative name.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="other_names",
                to="data.organization",
            ),
        ),
        migrations.AlterField(
            model_name="othername",
            name="person",
            field=models.ForeignKey(
                help_text="A link to the Person connected to this alternative name.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="other_names",
                to="data.person",
            ),
        ),
        migrations.AddConstraint(
            model_name="othername",
            constraint=models.UniqueConstraint(
                fields=("name", "start_date", "end_date", "organization_id"),
                name="unique_orgname",
            ),
        ),
        migrations.AddConstraint(
            model_name="othername",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("person_id__isnull", True),
                    ("organization_id__isnull", True),
                    _connector="XOR",
                ),
                name="personname_xor_orgname",
            ),
        ),
    ]
