# Generated by Django 4.1.1 on 2023-12-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0096_othername_organization_alter_othername_person_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="othername",
            name="personname_xor_orgname",
        ),
        migrations.AddConstraint(
            model_name="othername",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("organization_id__isnull", False), ("person_id__isnull", True)
                    ),
                    models.Q(
                        ("organization_id__isnull", True), ("person_id__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="personname_xor_orgname",
            ),
        ),
    ]
