# Generated by Django 4.1.1 on 2023-12-27 11:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0097_remove_othername_personname_xor_orgname_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="billsponsorship",
            name="person_organization",
        ),
    ]
