# Generated by Django 4.1.1 on 2023-12-27 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0098_remove_billsponsorship_person_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="billsponsorship",
            name="chamber",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chamber_sponsorships",
                to="data.organization",
            ),
        ),
    ]
