# Generated by Django 4.1.1 on 2023-12-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0099_billsponsorship_chamber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scrapereport",
            name="end_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="scrapereport",
            name="start_time",
            field=models.DateTimeField(null=True),
        ),
    ]
