# Generated by Django 4.1.1 on 2023-12-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0100_alter_scrapereport_end_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="runplan",
            name="end_time",
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="runplan",
            name="start_time",
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="runplan",
            name="success",
            field=models.BooleanField(db_index=True, default=False, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="scrapereport",
            unique_together={("plan", "scraper")},
        ),
    ]
