# Generated by Django 4.1.1 on 2024-01-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0102_sessiondataqualityreport_unmatched_sponsorships"),
    ]

    operations = [
        migrations.AddField(
            model_name="legislativesession",
            name="last_attempted_bills_scrape_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="legislativesession",
            name="last_attempted_events_scrape_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="legislativesession",
            name="last_attempted_votes_scrape_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="legislativesession",
            name="last_successful_bills_scrape_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="legislativesession",
            name="last_successful_events_scrape_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="legislativesession",
            name="last_successful_votes_scrape_at",
            field=models.DateTimeField(null=True),
        ),
    ]
