# Generated by Django 4.1.1 on 2024-01-11 01:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0106_remove_scrapednamematch_match_unique_with_chamber_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="scrapednamematch",
            name="match_unique_with_chamber",
        ),
        migrations.RemoveConstraint(
            model_name="scrapednamematch",
            name="match_unique_without_chamber",
        ),
        migrations.AddConstraint(
            model_name="scrapednamematch",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("matched_chamber__isnull", False),
                    ("matched_organization__isnull", False),
                ),
                fields=(
                    "legislative_session_id",
                    "matched_chamber_id",
                    "matched_organization_id",
                    "value",
                ),
                name="match_unique_organization_with_chamber",
            ),
        ),
        migrations.AddConstraint(
            model_name="scrapednamematch",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("matched_chamber__isnull", True),
                    ("matched_organization__isnull", False),
                ),
                fields=("legislative_session_id", "matched_organization_id", "value"),
                name="match_unique_organization_without_chamber",
            ),
        ),
        migrations.AddConstraint(
            model_name="scrapednamematch",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("matched_chamber__isnull", False),
                    ("matched_person__isnull", False),
                ),
                fields=(
                    "legislative_session_id",
                    "matched_chamber_id",
                    "matched_person_id",
                    "value",
                ),
                name="match_unique_person_with_chamber",
            ),
        ),
        migrations.AddConstraint(
            model_name="scrapednamematch",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("matched_chamber__isnull", True), ("matched_person__isnull", False)
                ),
                fields=("legislative_session_id", "matched_person_id", "value"),
                name="match_unique_person_without_chamber",
            ),
        ),
    ]
