# Generated by Django 4.1.1 on 2024-01-11 08:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        (
            "data",
            "0109_remove_scrapednamematch_match_unique_organization_with_chamber_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="scrapednamematch",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
