# Generated by Django 4.1.1 on 2024-01-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0110_scrapednamematch_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scrapednamematch",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
