# Generated by Django 4.1.1 on 2024-02-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0111_alter_scrapednamematch_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personoffice",
            name="classification",
            field=models.CharField(
                choices=[
                    ("district", "District Office"),
                    ("district-mail", "District Mailing Address"),
                    ("capitol", "Capitol Office"),
                    ("capitol-mail", "Capitol Mailing Address"),
                    ("primary", "Primary Office"),
                    ("home", "Home"),
                ],
                max_length=20,
            ),
        ),
    ]
