# Generated by Django 4.1.1 on 2024-08-10 22:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0112_alter_personoffice_classification"),
    ]

    operations = [
        migrations.AddField(
            model_name="legislativesession",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="legislativesession",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="billdocument",
            name="note",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="billversion",
            name="note",
            field=models.TextField(),
        ),
    ]
